In [1]:
import numpy as np
from numpy import genfromtxt

In [4]:
data=genfromtxt(r'C:\Users\Kuttan\Downloads\Python CVCourse\Python CV_Course\Computer-Vision-with-Python\DATA\bank_note_data.txt',delimiter=',')

In [5]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [8]:
labels=data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [9]:
features=data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [10]:
X=features
y=labels#these variables are used conventionally

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [15]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [16]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [17]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

In [21]:
len(X_train),len(X)#so 100-33=67% of X is in X_train

(919, 1372)

In [22]:
len(X_test),len(X)#so 33 % of X is in test data(as said in above train_test_split())

(453, 1372)

In [23]:
#As the valuse in each are scattered, as a part of standardization, we are scaling
#the data using MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

In [25]:
scaler_object=MinMaxScaler()

In [27]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [28]:
scaled_X_train=scaler_object.transform(X_train)
scaled_X_test=scaler_object.transform(X_test)

In [29]:
scaled_X_train.max()

1.0000000000000002

In [30]:
scaled_X_train.min()

0.0

In [31]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [32]:
#creation of neural network
model=Sequential()
model.add(Dense(4,input_dim=4,activation='relu'))#Creation of input layers with 4 neurons
model.add(Dense(8,activation='relu'))#creation of hidden layers with 8 neurons
#usually for simple things, 2x hidden layer neurons are used. ir 2 times of input 
model.add(Dense(1,activation='sigmoid'))#creation of ouptput layer which as you could
#expect to be just 1 neuron with a value of 0 or 1 which is why we are using sigmoid function


In [34]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [37]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)#verbose prints along when its printing

Epoch 1/50
 - 2s - loss: 0.6938 - acc: 0.4831
Epoch 2/50
 - 0s - loss: 0.6906 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6888 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6872 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6856 - acc: 0.5495
Epoch 6/50
 - 0s - loss: 0.6843 - acc: 0.5495
Epoch 7/50
 - 0s - loss: 0.6825 - acc: 0.5495
Epoch 8/50
 - 0s - loss: 0.6806 - acc: 0.5495
Epoch 9/50
 - 0s - loss: 0.6783 - acc: 0.5495
Epoch 10/50
 - 0s - loss: 0.6757 - acc: 0.5495
Epoch 11/50
 - 0s - loss: 0.6727 - acc: 0.5495
Epoch 12/50
 - 0s - loss: 0.6692 - acc: 0.5604
Epoch 13/50
 - 0s - loss: 0.6650 - acc: 0.5691
Epoch 14/50
 - 0s - loss: 0.6595 - acc: 0.5822
Epoch 15/50
 - 0s - loss: 0.6513 - acc: 0.6017
Epoch 16/50
 - 0s - loss: 0.6348 - acc: 0.6257
Epoch 17/50
 - 0s - loss: 0.6213 - acc: 0.6409
Epoch 18/50
 - 0s - loss: 0.6101 - acc: 0.6431
Epoch 19/50
 - 0s - loss: 0.5986 - acc: 0.6529
Epoch 20/50
 - 0s - loss: 0.5869 - acc: 0.6529
Epoch 21/50
 - 0s - loss: 0.5757 - acc: 0.6529
Epoch 22/50
 - 0s - lo

In [47]:
#model.predict_classes(scaled_X_test)

In [40]:
model.metrics_names

['loss', 'acc']

In [42]:
from sklearn.metrics import confusion_matrix,classification_report

In [69]:
predictions=model.predict_classes(scaled_X_test)

In [46]:
confusion_matrix(y_test,predictions)

array([[254,   3],
       [ 20, 176]], dtype=int64)

In [48]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.93      0.99      0.96       257
        1.0       0.98      0.90      0.94       196

avg / total       0.95      0.95      0.95       453



In [49]:
model.save('mysupermodel.h5')

In [50]:
from keras.models import load_model

In [51]:
newmodel=load_model('mysupermodel.h5')

In [57]:
newmodel

In [60]:
#newmodel.predict_classes(scaled_X_test)